linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gocritic
    - revive
    - errorlint
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - bodyclose
    - noctx
    - prealloc
    - unconvert
    - misspell

linters-settings:
  govet:
    enable-all: true
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

run:
  timeout: 5m
